pdflatex thesis.tex;
#bibtex chapters/chapter1-introduction/chapter1-introduction;
#bibtex chapters/chapter2-genetic-architecture/chapter2-genetic-architecture;
#bibtex chapters/chapter3-allele-specific-expression/chapter3-ase;
#bibtex chapters/chapter4-deconvolution/chapter4-deconvolution;
bibtex chapters/chapter5-brain-eqtls/chapter5-brain-eqtls;
#bibtex chapters/chapter6-discussion/chapter6-discussion;
pdflatex thesis.tex;
pdflatex thesis.tex
